### ISSUE TITLE
Make theme linux only

### ISSUE THREAD

**Issue by HeikoAdams** [horst3180/arc-firefox-theme#1]
Since the gtk-theme is only available on linux it doesn't make sense to mark the theme(s) plattform independent.

**Comment by HeikoAdams** [comment]
Adding "<em:targetPlatform>Linux</em:targetPlatform>" should do the trick

**Comment by horst3180** [comment]
Fixed with https://github.com/horst3180/arc-firefox-theme/commit/0446c2e11ab6cadb17da7c09313eee226dcc40e1. I added the BSD's too, since they have GTK aswell.
