### ISSUE TITLE
Not looking good with "The Fox" extension

### ISSUE THREAD

**Issue by ZJaume** [horst3180/arc-firefox-theme#11]
When "hide the navigation bar" option is activated in The Fox, Only Better Options extension the navigation bar doesn't look fully themed.
![captura de pantalla de 2015-08-24 14-45-52](https://cloud.githubusercontent.com/assets/11339330/9440367/de5c2802-4a6e-11e5-9f90-eee60a8bcc5a.png)

**Comment by lucaswerkmeister** [comment]
The extension is now called [Beyond Australis](https://addons.mozilla.org/en-US/firefox/addon/the-fox-only-better/?src=search) btw.
