### ISSUE TITLE
Firefox 53.0.2 not working (Not supported)!

### ISSUE THREAD

**Issue by McLOVIN892MOMONAST** [horst3180/arc-firefox-theme#119]
I've been working as a software developer for a company for 18 months now. It's my first job since I graduated college. I never wanted to be a programmer and never really enjoyed it, but just picked it because I was trying to get into another program and everyone told me that this would land me a good job. I had to pick a major or else forfeit my scholarship. I never ended up getting accepted into the program I wanted to be in, so I eventually just finished up my CS degree.

Ever since I first started working here I felt like I didn't belong. It was a month before I was given any work. I've never been given any sort of training or explanation for the work I'm given. I'm usually given an assignment each month with one sentence explaining what needs to be done and I'm left to figure out the rest. It's usually pretty simple stuff, but since I'm completely unfamiliar with what I'm working with, it can feel like a huge project. I've brought up many times in meetings and to my supervisor that I feel like I'm not getting enough explanation to go along with my work, but nothing has been done.

I work with around 30 other people in my office. Everyone is 10+ years older than me. It makes it hard to connect with them and I feel like an outcast. It feels like everyone views me like I'm not supposed to be here. Besides them assigning me work, it feels like they forget I'm here or just ignore me. Whenever I try to ask for help with something, I'll either just get a sarcastic response or they'll seem annoyed that I'm bothering them.

I've always been unhappy since I've been here, and there have been some really rough times. I'm constantly anxious that I'm not going to be able to do my work. I feel like I have no idea how to do it. I have 24/7 anxiety which leads into depression. I typically go home after work and do pretty much nothing until I go to bed because I'm simply too depressed and have no motivation. It's started to make me physically feel sick and I've been having thoughts of suicide. Most days on my way to work I contemplate crashing my car so I'll have a legitimate reason not to be there.

I try to explain how I feel to my girlfriend and parents, but they just tell me they want me to be happy, but I can't quit until I find something else. I can understand that, as I have rent, bills, and a car payment to pay. I haven't found anything, though. I've been looking for weeks for jobs, but haven't found anything to even apply to. I'd love to switch fields, but that feels impossible without another degree. Everything I look for that relates to my degree is programming related, and I know I don't want to get myself back into the same situation. I desperately tell them that I'm so unhappy and the anxiety is killing me and I just want to quit, but they tell me I shouldn't.

I understand their reasoning and know the decision to quit is my own, but it makes it hard when I feel like I don't have their support if I choose that.
What should I do? Is quitting a horrible idea that will be detrimental to my chances of getting hired again in the future? Please help me.

**Comment by GrindamN** [comment]
Hmm, what about moving to another area in IT, say DevOps or Business Development?
