### ISSUE TITLE
Some text entry fields look out of place in dark version

### ISSUE THREAD

**Issue by worzel666** [horst3180/arc-firefox-theme#12]
Some text/data forms look broken using the arc-dark version.
![Facebook chat](http://i.imgur.com/i2WqUth.png)
![Arch Linux login](http://i.imgur.com/7dg9rWR.png)

**Comment by horst3180** [comment]
Yea, that's a common problem with firefox and dark themes. As a workaround you could try this http://knusper.net/knusperblog/2014/firefox-gtk-dark-theme-fix/
I will try to fix this on the theme level, so this workaround hopefully won't be needed when I'm done.

**Comment by francoism90** [comment]
Web-designers should include a background code for input, same for other elements.
Nothing to do about this.
