### ISSUE TITLE
Windows Arc

### ISSUE THREAD

**Issue by FerVillanuevas** [horst3180/arc-firefox-theme#127]
Hello, I am noob, I have adapted the theme for windows, you could say that it is the ver .0.1 hehe, use the updated repository, thanks to horst3180
Here is the zip download

[Arc-Windows](https://drive.google.com/file/d/0B674BwKAQLJ4SGtHVlhSc005ajQ/view?usp=sharing)

**Comment by sinankizar** [comment]
Nice try mate. I think it is just the white theme? Can you please do this for the Arc Dark? And the window controls (close, minimize, maximize) need a bit moving to the right.
