### ISSUE TITLE
Not Compatible with Firefox Nightly (43.x)

### ISSUE THREAD

**Issue by MichaelTunnell** [horst3180/arc-firefox-theme#13]
I am currently trying to use your theme in Firefox Nightly (43.x) but unfortunately it does not work.

**Comment by francoism90** [comment]
Running fine here on the latest nightly. You just have to compile it yourself, see instructions. :)

**Comment by horst3180** [comment]
I bumped the maxVersion to 43.\* in the latest release. It should install fine, but there are some small glitches with that Firefox version.

**Comment by TheInitializer** [comment]
The AMO page says it's not compatible with FF 41...

**Comment by horst3180** [comment]
Update your system. Firefox 46 is the newest version in the Fedora repos. If you don't want that, you can search for old versions on the AMO page or install the xpi from [here.](https://github.com/horst3180/arc-firefox-theme/releases/tag/41.20151101)
