### ISSUE TITLE
Search field border radius 

### ISSUE THREAD

**Issue by bmeznarsic** [horst3180/arc-firefox-theme#14]
searchbar-textbox border radius in arc-firefox-theme-40.20150826.xpi is still round.
![zaslonska slika 2015-08-28 11-14-23](https://cloud.githubusercontent.com/assets/6306479/9543056/f5f563e8-4d75-11e5-8697-948b3f6d123b.png)

**Comment by horst3180** [comment]
Yes, I know. I left search entries rounded, because why not :)
