### ISSUE TITLE
This repo need to be supported in 60

### ISSUE THREAD

**Issue by Aragami1408** [horst3180/arc-firefox-theme#140]
I'm using Firefox 60 now! Can you pls release 60.x version of arc

**Comment by ArchangeGabriel** [comment]
What is wrong with default theme? Also this theme cannot be ported to Firefox > 56.

**Comment by Aragami1408** [comment]
It said this plugin is not compatible in firefox 60

**Comment by ArchangeGabriel** [comment]
Yes, that’s normal. But you don’t need it.

**Comment by Aragami1408** [comment]
But it couldn't run in my firefox but chrome could

**Comment by ArchangeGabriel** [comment]
You don’t need to run it in Firefox, the default theme is now using system GTK theme.
