### ISSUE TITLE
Theme not working with Firefox 40.0.2 in Archlinux

### ISSUE THREAD

**Issue by elzoona** [horst3180/arc-firefox-theme#15]
Back and Forward buttons nos working, and others problems you can see in the image.

![captura de pantalla de 2015-08-28 16-20-13](https://cloud.githubusercontent.com/assets/165352/9555015/ae380292-4da0-11e5-879e-7833546eba4a.png)

**Comment by horst3180** [comment]
Looks like your `userChrome.css` is interfering with the theme. Remove/rename your `~/.mozilla/firefox/*.default/chrome` folder and restart Firefox.

**Comment by elzoona** [comment]
oK, feeling pretty stupid for not thinking on that! Problem fixed. Thanks a lot for such a quick response!
