### ISSUE TITLE
Can't install latest release of this theme to FF40.0.3

### ISSUE THREAD

**Issue by kingtosh** [horst3180/arc-firefox-theme#16]
I can't install latest versions to FF40.0.3 running on mac os x.

**Comment by francoism90** [comment]
Don't think OS X is supported, see Readme:
"Note: This theme is meant to be used in conjunction with the Arc GTK theme, don't use it with other GTK themes or it will look broken."

**Comment by giantspeck** [comment]
I've never had significant issues using Linux-only Firefox themes in OS X before.

**Comment by horst3180** [comment]
The theme should now install on all platforms. See here https://github.com/horst3180/arc-firefox-theme/releases/tag/40.20150911
There may be bugs, because I can test it only on Linux.

**Comment by giantspeck** [comment]
It actually seems to work pretty well on Windows except for a couple glaring bugs.  I'll have to try it on OS X and see if it works better there.
