### ISSUE TITLE
Dark theme has black text in dark input fields.

### ISSUE THREAD

**Issue by WegDamit** [horst3180/arc-firefox-theme#19]
see
![screenshot-bug 2015-09-15 09-40-22](https://cloud.githubusercontent.com/assets/53998/9870628/f8515c3e-5b8d-11e5-83c7-bc61d324eba9.png)

Linux, Ubuntu 15.05, Gnome 3.16  and FF 40.0.3.

I know there are some chrome css styles to override these settings but did not found them again for a quick fix... :(

**Comment by sunng87** [comment]
If I understand correctly, this is a gtk theme issue. Or more correctly, this a CSS issue that the input inherits the body text color assuming the input background is white.

**Comment by horst3180** [comment]
See here for a workaround: http://knusper.net/knusperblog/2014/firefox-gtk-dark-theme-fix/
Basically this is a very old firefox bug with dark themes.
