### ISSUE TITLE
Pubishing on AMO

### ISSUE THREAD

**Issue by agilob** [horst3180/arc-firefox-theme#2]
Do you consider publishing your theme on AMO? It could be signed by Mozilla and users wouldn't have to worry about having "untrusted" addon.

**Comment by horst3180** [comment]
I'm not sure if themes have to be signed. Right now I'm using Firefox 40 with `xpinstall.signatures.required` set to `true` and it doesn't complain.

**Comment by agilob** [comment]
As far as I know this option will be removed in two versions of Firefox and will be available only on developer edition. I also don't know if themes have to be signed, but anyway it would be good to have it on AMO for automated updates ;)

**Comment by horst3180** [comment]
Yes, I agree. I want to upload it to AMO either way.

**Comment by agilob** [comment]
Any progess on this?

**Comment by horst3180** [comment]
It's in the review process. I can't give an eta how long it will take though.

**Comment by horst3180** [comment]
So, the review process took a _bit_ longer than I expected, but it's available on AMO now.

**Comment by agilob** [comment]
thanks o/
