### ISSUE TITLE
Old window icons showing when maximized at Darket-Theme

### ISSUE THREAD

**Issue by ZJaume** [horst3180/arc-firefox-theme#20]
The icons aren't correct when maximized window
![captura de pantalla de 2015-09-17 14-09-29](https://cloud.githubusercontent.com/assets/11339330/9932629/bd1963c8-5d45-11e5-8996-bc03463ea915.png)
instead of (when not maximized windof)
![captura de pantalla de 2015-09-17 14-10-14](https://cloud.githubusercontent.com/assets/11339330/9932650/e717f6d0-5d45-11e5-8830-d73c9be09a81.png)

40.20150911 version

**Comment by horst3180** [comment]
Which distro is this? I know that Ubuntu does something to undecorate maximized Firefox windows, but those buttons should be styled. I'll have to look into that.

**Comment by ZJaume** [comment]
Arch Linux with GNOME 3.16

**Comment by ZJaume** [comment]
I have tested the other versions(dark and normal) and they look fine.

**Comment by ZJaume** [comment]
Sorry,  i have rebooted again and now darker theme looks good when maximized window.
