### ISSUE TITLE
Small menu icons on hidpi screens

### ISSUE THREAD

**Issue by joeplus** [horst3180/arc-firefox-theme#21]
Hi,
I am using a Dell XPS 13 with Ubuntu 15.04 and Gnome 3.14.4 and the icons in the top right corner appear very slow. I am also using the Arc GTK3 theme and the Arc gnome shell theme.

Here is a screenshot showing what I meant in the top right corner.

![screenshot from 2015-09-17 23 51 31](https://cloud.githubusercontent.com/assets/7793652/9947183/784a487c-5d98-11e5-8370-bf837b055d4f.png)

**Comment by horst3180** [comment]
Actually that was a bug in the Arc gtk theme, but it has been fixed.
