### ISSUE TITLE
Not working on Firefox 44

### ISSUE THREAD

**Issue by aronnebrivio** [horst3180/arc-firefox-theme#23]
Arch theme is not working with Firefox 44, can you please add support for this browser version? Thanks

**Comment by horst3180** [comment]
I bumped the maxVersion to 44 in the `firefox-41-beta` branch. I will move it into master tomorrow when firefox 41 gets released.
You can checkout that branch and build it yourself, though.

Note: I only enable the higher versions for testing, so there may be glitches.

**Comment by aronnebrivio** [comment]
Just built manually, it's working fine, thanks!
