### ISSUE TITLE
Firefox Hello icon broken

### ISSUE THREAD

**Issue by lucaswerkmeister** [horst3180/arc-firefox-theme#24]
This is how it looks in the navigation bar:
![screenshot from 2015-09-22 14-25-16](https://cloud.githubusercontent.com/assets/2346599/10018286/cc1635ec-6135-11e5-830c-985a8113f319.png)

And this is how it looks in the Customize screen:
![screenshot from 2015-09-22 14-26-47](https://cloud.githubusercontent.com/assets/2346599/10018314/ff8b5e2a-6135-11e5-98a0-c57e665c7d2f.png)
(the label is also gone)

Happens even if I manually disable all add-ons, so I don’t think it’s related to any other add-ons I have installed. (Doesn’t happen if you “Restart with Add-ons Disabled”, since that disables the theme too.)

**Comment by horst3180** [comment]
is that Firefox 40?

**Comment by lucaswerkmeister** [comment]
42, current Developer Edition

**Comment by horst3180** [comment]
I'll create a branch for Firefox 42 beta and sync with the latest changes.

**Comment by lucaswerkmeister** [comment]
So this doesn’t happen in Firefox 40?

**Comment by horst3180** [comment]
No, it doesn't happen in 41 either. It has to be a change introduced in 42.

**Comment by horst3180** [comment]
I created a branch for Firefox 42: https://github.com/horst3180/arc-firefox-theme/tree/firefox-42-beta
To test this, you have to checkout this branch and generate the .xpi files yourself as described in the readme, i.e

```
git clone https://github.com/horst3180/arc-firefox-theme && cd arc-firefox-theme
git checkout firefox-42-beta
./autogen.sh --prefix=/usr
make mkxpi
```

**Comment by lucaswerkmeister** [comment]
Seems to work, thanks! (Also fixes a problem with the Sync row in the menu.)

**Comment by lucaswerkmeister** [comment]
Oh, I found another problem: The “tab audio” icon (see [Bug 486262](https://bugzilla.mozilla.org/show_bug.cgi?id=486262)) always takes up space, and when clicked also becomes visible, even for tabs that don’t play audio. This is especially noticeable for pinned tabs, which are almost twice as wide as they should be.

**Comment by horst3180** [comment]
It should work now (https://github.com/horst3180/arc-firefox-theme/commit/8535b34aea92c3d983e24fa094ff9a8200e848e3).

Tested with 42.0b1 and 43.0a2.

**Comment by lucaswerkmeister** [comment]
Great, thanks!
