### ISSUE TITLE
HTitle Extension Support

### ISSUE THREAD

**Issue by craftycorvid** [horst3180/arc-firefox-theme#27]
The Gnome-Firefox theme detects when you are using the HTitle extension to hide the title bar and renders its own Close, Maximize and Minimize buttons, mimicking the appearance of apps that use Client-Side Decorations. 

I would be great to have this functionality added to the Arc Theme.

**Comment by horst3180** [comment]
It does have HTitle support. This is how it looks for me
![bildschirmfoto von 2015-10-12 13-24-33](https://cloud.githubusercontent.com/assets/8473629/10426876/b53f458e-70e4-11e5-8ee5-5efd42ad0654.png)

**Comment by craftycorvid** [comment]
Oh, you are right, the window controls are displayed on the tab bar. The Gnome-Firefox theme moves the tab bar to the bottom and displays window controlls to the right of the menu button to mimic how Gnome Browser looks.

This issue comes up when using HTitle and an extension like Tab Tree or Tree Style Tabs that hides the standard tab bar.

**Comment by craftycorvid** [comment]
So, after doing some more research, it seems like this should be fixed in the Tab Tree and Tree Style Tabs extensions. HTitle has a way of detecting were to draw its buttons using certain attributes that are not being set by those extensions.

**Comment by khoerodin** [comment]
How to move window control button (minimize,maximize,close) to left?
