### ISSUE TITLE
Loading spinner animation on tabs not shown

### ISSUE THREAD

**Issue by Abdillah** [horst3180/arc-firefox-theme#28]
In white style, no animation spinner shown during page load. 
Is it missing or hasn't been added?

Using latest release (Release 41.20150921) available.

![loading-not-shown](https://cloud.githubusercontent.com/assets/3030950/10456329/ff8619b8-71ea-11e5-82d4-8b900d410f27.png)

**Comment by arshavindn** [comment]
This happens to me too.

**Comment by horst3180** [comment]
~~I works for me. Are you running Firefox 41?~~
Now I'm having that problem too. I've been using Firefox 42 beta for a few weeks so I didn't notice this.

**Comment by horst3180** [comment]
This has been fixed with https://github.com/horst3180/arc-firefox-theme/commit/1b65385ef744d692cac6ed706b0ac7532b2fbb49. You can build the .xpi files yourself as described in the readme if you don't want to wait for a new release.
