### ISSUE TITLE
Make a new spinner for dark theme

### ISSUE THREAD

**Issue by adiultra** [horst3180/arc-firefox-theme#32]
The spinner used in the theme is that of the firefox's default theme, which looks out of the place in the dark version: 

![screenshot from 2015-11-01 19 12 34](https://cloud.githubusercontent.com/assets/12121575/10869187/07bb7ad8-80cd-11e5-8968-9c54303ba8a0.png)

Please make a new spinner that is better and BLUER.

**Comment by horst3180** [comment]
New loading spinner has been added. https://github.com/horst3180/arc-firefox-theme/commit/3bf46267cc23c76d287fee72519da293acde8ca3
