### ISSUE TITLE
Firefox 42.0 glitches

### ISSUE THREAD

**Issue by alxlion** [horst3180/arc-firefox-theme#34]
After Firefox updates to 42, some glitches appeared in the interface (disappears when changing to default theme).
### Label counter

![capture d ecran_2015-11-04_12-54-15](https://cloud.githubusercontent.com/assets/1835726/10937487/609e6eda-82f3-11e5-9560-ad21bbcb4e90.png)
### Firefox Hello icon

![capture d ecran_2015-11-04_12-54-53](https://cloud.githubusercontent.com/assets/1835726/10937499/71292880-82f3-11e5-8cf4-08b1fa8da2ba.png)

**Comment by horst3180** [comment]
Did you install the latest release? https://github.com/horst3180/arc-firefox-theme/releases/tag/42.20151103
Soon the theme will be available on addons.mozilla.org and updating will be a lot smoother.

**Comment by alxlion** [comment]
Oh yes, I had forgotten that the updates were not automatic.Thanks !

Fixed.
