### ISSUE TITLE
Link to addons.mozilla.org takes to the german page

### ISSUE THREAD

**Issue by bugalo** [horst3180/arc-firefox-theme#36]
Hi,

I've noticed that the link to the installation in addons.mozilla.org takes to the german page:

https://addons.mozilla.org/de/firefox/collections/horst3180/a/

Is this intentional? The page in English is 

https://addons.mozilla.org/en/firefox/collections/horst3180/a/

**Comment by horst3180** [comment]
Fixed. I didn't pay attention when copying the link. Somehow it always refers me to the German page even if I click the English link.

**Comment by wilfm** [comment]
Didn't know about the extension page :) But you may want add a thing for Windows/Mac/old Linux users cos otherwise you are going to get a lot of confused reviews (due to the titlebar etc not changing)

**Comment by horst3180** [comment]
The extension is only installable on Linux. There are some bugs on Windows and OS X that I can't fix without help. Restricting the target platform was the only way to get it approved.
