### ISSUE TITLE
Mozilla plans to remove support for themes

### ISSUE THREAD

**Issue by Corsseir** [horst3180/arc-firefox-theme#37]
http://www.ghacks.net/2015/11/08/mozilla-plans-to-remove-support-for-heavyweight-themes-in-firefox/

Is that mean this theme already dead?

**Comment by francoism90** [comment]
Midori is a good alternative. :)

**Comment by Algram** [comment]
No it isn't. As soon as you want to have a bookmark toolbar you are done.

**Comment by francoism90** [comment]
Palemoon seems to be a good fork then. ;)
Found Midori crashing a lot, it may take a few years for it to be stable.

What are the devs at Mozilla doing? :/

**Comment by Lootyhoof** [comment]
Just FYI about Pale Moon from a dev perspective: for the UI, it's mostly based on Firefox 24's. If you wanted to directly port this, a few things would need changing and others removed; it might be better to just start from scratch for the styles. That's not to say a port isn't possible, of course (see [here](https://github.com/Lootyhoof/australium/tree/win10), I ported Australis), just might not be the easiest route.

If you do embrace Pale Moon, we welcome you with open arms. :)

**Comment by ghost** [comment]
That Ghacks article is mostly rubbish. It is true that XUL is being deprecated, but what isn't mentioned in the article is that it will be replaced with another set of stable APIs for theming, not just personas. This might even make it easier, as the stable APIs should break less often.
