### ISSUE TITLE
Tabs broken in dark and darker

### ISSUE THREAD

**Issue by Darksonn** [horst3180/arc-firefox-theme#4]
In the dark and darker themes, the tab line does not at all look like the screenshots. They're white and I cannot read the labels on anything but the selected tab.

![scr](https://cloud.githubusercontent.com/assets/928074/9386934/3b911d8e-475e-11e5-9157-a75589a826ef.png)

Howevering over a tab also makes it possible to see the labels.  
The normal theme works fine.

**Comment by horst3180** [comment]
You have to use the Arc Darker/Arc Dark GTK theme in combination with the Firefox theme. Right now the Firefox theme relies on some styles set by the GTK theme, but I will probably change that and make the Firefox theme more standalone.

**Comment by horst3180** [comment]
It should be fixed now.
