### ISSUE TITLE
Cannot install on firefox 42

### ISSUE THREAD

**Issue by prab4th** [horst3180/arc-firefox-theme#43]

**Comment by horst3180** [comment]
Yea, I updated to Firefox 43 a bit too soon. You can select an older version by clicking the Add to Firefox button. Version 42.20151103 should be fine.

**Comment by emartinezpinzon** [comment]
Ah?

2016-01-26 12:13 GMT-05:00 horst3180 notifications@github.com:

> Closed #43 https://github.com/horst3180/arc-firefox-theme/issues/43.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/horst3180/arc-firefox-theme/issues/43#event-526795059
> .

## 

_Con los ojos se puede ver el horizonte, pero con el corazón se puede ver
más allá._

_Emanuel Martínez Pinzón_

**Comment by horst3180** [comment]
What? This issue is no longer valid.
