### ISSUE TITLE
does not work properly on OSX 

### ISSUE THREAD

**Issue by muhasturk** [horst3180/arc-firefox-theme#5]
Is there a way to apply for OSX?

**Comment by horst3180** [comment]
The theme should now install on all platforms. See here https://github.com/horst3180/arc-firefox-theme/releases/tag/40.20150911
There may be bugs, because I can test it only on Linux.

**Comment by muhasturk** [comment]
I've just checked on OSX 10.10.5 and latest stable Firefox 40.0.3. Still here

https://yadi.sk/i/Pm1CXwIdj3AkX
https://yadi.sk/i/bJmkdmSNj3Akb
https://yadi.sk/i/_Ybu4cwFj3Akf
