### ISSUE TITLE
Possible bug: "add-ons" menu poorly re-styled when using "arc-dark" with All-In-One-Sidebar

### ISSUE THREAD

**Issue by alan12345678** [horst3180/arc-firefox-theme#53]
I think the problem might be caused by this extension and not that one, but haven't found a way of testing it. This link might be related (another issue in FF with theming):

https://bugzilla.mozilla.org/show_bug.cgi?id=483972

Overall the theme has installed and works perfectly UNTIL I install this additional plug-in "All-In-One-Sidebar", at which point the tab that opens in FF to show installed add-ons changes from having large panels and clear type for each extension/plug-in etc. to showing only very narrow stacked panels with dark text on dark background.

I'm using FF 45.0.2 on gnome3.18.2

**Comment by aiguofer** [comment]
Oh wow... I've always had this problem and finally decided to report it... didn't know that things actually looked well with all-in-one-sidebar disabled.

I've had this for a while, and it continues with FF 51. I'm also on Gnome (3.22).

**Comment by alan12345678** [comment]
My solution - which doesn't directly address the issue - was to use Omni-Sidebar instead. The problem goes away. Sadly though, most or all such extensions will stop working in FF57, so I'll dump it and go for Vivaldi :0/
