### ISSUE TITLE
Address suggestion box looks odd

### ISSUE THREAD

**Issue by frysztak** [horst3180/arc-firefox-theme#54]
I suppose that title says it all. Here's a screenshot:
![fx](https://cloud.githubusercontent.com/assets/217806/14868733/6cc72998-0ccf-11e6-8f3a-1229a1b9499c.png)

Issue occurs on Firefox 48, but not on 46. GTK version is 3.20 and arc-theme is up-to-date. Suggestion box in default theme looks okay.

**Comment by horst3180** [comment]
It's a bit of a late reply, I know, but this is now the default appearance of the suggestion box and I added proper support some time ago.
