### ISSUE TITLE
Tooltip background has wrong color

### ISSUE THREAD

**Issue by freundTech** [horst3180/arc-firefox-theme#56]
I'm using the newest Version of this theme (build from source).

The tooltips when hovering over UI elements have a light gray, hard to see background, while in gtk applications when using the Arc gtk theme they have a dark gray background.

Here are some pictures:

Tooltip in firefox
![screenshot from 2016-04-29 20-03-31](https://cloud.githubusercontent.com/assets/9515067/14925208/99028246-0e46-11e6-9b71-289d8450a789.png)

Tooltip in gtk (gedit)
![screenshot from 2016-04-29 20-03-56](https://cloud.githubusercontent.com/assets/9515067/14925209/99054080-0e46-11e6-8b31-af4336201c6c.png)

**Comment by horst3180** [comment]
That's a Firefox bug. Firefox has problems with GTK 3.20, but they're working on a fix.
