### ISSUE TITLE
Missing icons for Firefox Hello and Pocket?

### ISSUE THREAD

**Issue by belenos** [horst3180/arc-firefox-theme#57]
This is happening since after the last update. It's loading the default theme icons. Can you fix it please?

![screenshot from 2016-05-11 12-21-20](https://cloud.githubusercontent.com/assets/1954831/15186310/eb5f0142-1772-11e6-9e86-6a8003059296.png)

**Comment by horst3180** [comment]
Should be fixed with today's commits. I'll release an update shortly.
