### ISSUE TITLE
Firefox Nightly 49

### ISSUE THREAD

**Issue by rahilwazir** [horst3180/arc-firefox-theme#59]
It's not compatible with Firefox Nightly 49.x

> Not available for Firefox 49.0

Can you please make it so?

**Comment by p-boiko** [comment]
I'm on a Nightly channel too
https://screencloud.net/v/7W29
I doubt there are any issues other then a version number in a configuration file... Am I right?

**Comment by p-boiko** [comment]
Thank You for v49 support, but as of yesterday the current Nightly version is 50 already :)
I tried to modify manifest, but Firefox removes that addon immediately. Some kind of protection? Anyway, please make it independent on a version :)
Thank You in advance.

**Comment by p-boiko** [comment]
Well, I just cloned it, changed max version and followed the installation instructions. Rahil, you may close the issue

**Comment by rahilwazir** [comment]
@p-boiko Why? should wait for official release though

**Comment by slyscorpion** [comment]
@rahilwazir Firefox 50 is officially released as of November 15th 2016 :)

**Comment by rahilwazir** [comment]
@slyscorpion Yeah, time to close :smile:
