### ISSUE TITLE
search field without borders on the right side

### ISSUE THREAD

**Issue by AnderRasoVazquez** [horst3180/arc-firefox-theme#6]
I'm using "dark theme".

![seleccion_001](https://cloud.githubusercontent.com/assets/3936719/9399518/ede642be-47b5-11e5-82fd-6193665a23e8.jpg)

**Comment by horst3180** [comment]
Is that the ctrl+f searchbar? Because on my system it has buttons connected to it on the right.

**Comment by horst3180** [comment]
Ah nevermind I had to alter a setting to get this searchbar

**Comment by horst3180** [comment]
It's fixed with https://github.com/horst3180/arc-firefox-theme/commit/dd75577883478eedd87461d6800c5069d9e07e25 in `master`.
