### ISSUE TITLE
Not Compatible; Firefox 45.0.2

### ISSUE THREAD

**Issue by BrokenGabe** [horst3180/arc-firefox-theme#60]
Running Manjaro 15.12 XFCE with Arc Theme.
I attempted to install the firefox theme and it's not compatible with 45.0.2.
Please update/fix.

Note: Awesome theme btw keep up the great work!

**Comment by horst3180** [comment]
You should update your system, Firefox 45 is outdated. If you don't want that, you can download older versions from the [releases page](https://github.com/horst3180/arc-firefox-theme/releases).
