### ISSUE TITLE
Thunderbird support

### ISSUE THREAD

**Issue by AnderRasoVazquez** [horst3180/arc-firefox-theme#7]
All the great themes I see are for Firefox but Thunderbird never gets some love. Would be great to see this theme on it.

I'm using Arc theme on my Arch Linux but it doesn't look as great as it could be...

![seleccion_002](https://cloud.githubusercontent.com/assets/3936719/9399608/423432b2-47b7-11e5-8821-784dca5adc65.jpg)

Keep up the good work! =D

**Comment by KabbAmine** [comment]
:+1:  for Thunderbird support.

@AnderRasoVazquez Check the wonderful [TT DeepDark](https://addons.mozilla.org/en-us/thunderbird/addon/tt-deepdark/), I'm using it for more than 3 years, and its clearly the best theme here.

**Comment by AnderRasoVazquez** [comment]
Wow it's great! Thanks a lot ^^

**Comment by ralgozino** [comment]
+1 to Thunderbird support, please!

(I would love to see a Plasma 5 port too.. but iI know it's a lot to ask)

**Comment by HaoZeke** [comment]
TT DeepDark is excellent, but sometimes its hard to read..

**Comment by KabbAmine** [comment]
@HaoZekev Personally, I've never had problems with reading using it.

**Comment by ghost** [comment]
The first thing I thought about when I saw the FireFox Theme.
Sadly there are almost no good themes for Thunderbird :(
Like @KabbAmine I'm using TT Deep Dark for almost a year now....
PLEASE MAKE IT REAL!

**Comment by MichaelTunnell** [comment]
I would like to join in on the begging for Thunderbird theme because Arc is very nice and when you run Thunderbird in a Dark layout via KDE it looks like utter garbage. I have tried TT Deep Dark and it is not good enough as it doesnt effect everything. I would rather just use a light theme in Thunderbird anyway though because emails are always expected to be light from the sender end but with the current state of Thunderbird that is just impossible.

**Comment by fsimerey** [comment]
+1 
The default tabs are very ugly and this theme could become the must have for thunderbird.

**Comment by severin-lemaignan** [comment]
+1!

**Comment by alxlion** [comment]
+1

**Comment by aquatix** [comment]
+1 O:)

**Comment by dominicpratt** [comment]
+1

**Comment by jcpsantiago** [comment]
+1 :+1:

**Comment by sunng87** [comment]
+1

**Comment by avitex** [comment]
:+1:

**Comment by neumannjan** [comment]
+1 :+1:

**Comment by hugommg** [comment]
:+1:

**Comment by Hvingelby** [comment]
+1

**Comment by der-daniel** [comment]
+1

**Comment by M4dGun** [comment]
+1

**Comment by El0d1n** [comment]
+1

**Comment by ikaros** [comment]
+1

**Comment by fabianalexisinostroza** [comment]
please a thunderbird theme ! :D

**Comment by inputsh** [comment]
+1

**Comment by jaybosamiya** [comment]
+1

**Comment by jinyeow** [comment]
+1

**Comment by amosbird** [comment]
+1

**Comment by yadaniyil** [comment]
+1:yum:

**Comment by cialu** [comment]
Thank you for the amazing work.
Thunderbird support is welcome too. ;-)

**Comment by freundTech** [comment]
+1

**Comment by gitgud-software** [comment]
Yeah, I need this to happen. Thunderbird is incredibly feature-rich but could use this to make it mesh with the rest of the theme.

**Comment by arshavindn** [comment]
+1

**Comment by fishears** [comment]
+1

**Comment by alxlion** [comment]
Please stop to spam +1. Feature is on the road.

**Comment by bmeznarsic** [comment]
I'm more concerned about the new e10s, WebExtensions API and axing of the customisation support that's coming down the stream. This theme will stop working on Firefox after that. I hope Mozilla at least provides some way for people to theme the browser.

**Comment by HeaDBanGer84** [comment]
+1 
Thunderbird support would be really great!

**Comment by antistic** [comment]
+1

**Comment by TheBaronHimself** [comment]
+1

**Comment by kmyi** [comment]
+1
Thunderbird support would be awesome :-)

**Comment by alxlion** [comment]
### Please use emoji thumbs up feature to support this issue and respect other subscribed contributor to not spam uselessly.

Thanks !

**Comment by abnayak** [comment]
+1

**Comment by horst3180** [comment]
I decided not to support thunderbird, because I know it's a pain to maintain (as is the Firefox theme, btw), sorry.

**Comment by alxlion** [comment]
[TT DeepDark ](https://addons.mozilla.org/en-US/thunderbird/addon/tt-deepdark/) can make the job.

**Comment by nicolafio** [comment]
For the ones who might be interested, I started to write a [very very simple integration](https://github.com/JD342/arc-thunderbird-integration). Nothing spectacular, but at least it changes the fugly tabs. In the following weeks I might put more work on it if I can find some time and there is interest.
