### ISSUE TITLE
Hard-to-Read-Text at bookmarks toolbar

### ISSUE THREAD

**Issue by vestingz** [horst3180/arc-firefox-theme#70]
Bookmarks and folders at bookmarks toolbar appear with dark text on dark background which makes them very hard to read. Is it possible to change the text colour?
![arc_dark](https://cloud.githubusercontent.com/assets/19933361/16424042/d6492ece-3d5e-11e6-9368-bc034f912884.png)

**Comment by shahamran** [comment]
I changed it by adding the following line to ~/.mozilla/firefox/$PROFILE/chrome/userChrome.css :
`#personal-bookmarks .bookmark-item > .toolbarbutton-text {color:#d3dae3!important}`
Where `#d3dae3` is the color of focused tab's title text, so it's really easy (for me) to read.

**Comment by vestingz** [comment]
Yep, works great. Thank you! :+1:
