### ISSUE TITLE
When the bookmarks dropdown menu overlaps you can't tell where it begin

### ISSUE THREAD

**Issue by jeremy447** [horst3180/arc-firefox-theme#75]
Hello,

When the bookmarks dropdown menu overlaps you can't tell where it begin:

![arc-firefox-bookmarks](https://cloud.githubusercontent.com/assets/17159065/17209909/e94d2f0c-54bf-11e6-8856-093a19af8782.png)

Thanks !

**Comment by jeremy447** [comment]
Maybe a 1px gray line at the top of the dropdown menu will do the trick ?

**Comment by horst3180** [comment]
That's not a Firefox bug. Basically that's the way the window manager draws shadows around GTK 2 menus and I have no control over it. In addition, GTK 2 is basically dead, so I doubt we'll see a fix for this.

**Comment by jeremy447** [comment]
Ok thank you.
