### ISSUE TITLE
Is it possible to decrease vertical space?

### ISSUE THREAD

**Issue by woohooatb** [horst3180/arc-firefox-theme#77]
I like the theme, it is clean and functional, but is it anyway possible to decrease vertical space? We gnome users have to suffer from lack of adequate vertical screen real state as you may know and I hope you can help us by decreasing few pixels on tab and address bar. IF it's possible of course! 

Thank you.

**Comment by horst3180** [comment]
I could probably shave off a few pixels here and there, but that wouldn't account for much. I suggest the [htitle](https://addons.mozilla.org/de/firefox/addon/htitle/) extension to hide the titlebar.
