### ISSUE TITLE
"OK" and "Cancel" button are small

### ISSUE THREAD

**Issue by jeremy447** [horst3180/arc-firefox-theme#78]
Hello,

It may be just an impression but with Firefox 48 it seem that the "OK" and "Cancel" button are smaller than before, at least in the downloads confirmation windows.

![capture d ecran de 2016-08-05 10-05-18](https://cloud.githubusercontent.com/assets/17159065/17430434/74ee0fba-5af4-11e6-8677-ecddfc9cd03c.png)

Thanks !

**Comment by jeremy447** [comment]
Maybe here too ("Supprimer le marque-page" "Terminer")

![capture du 2016-08-05 10-10-23](https://cloud.githubusercontent.com/assets/17159065/17430538/0765fc86-5af5-11e6-86aa-7b15230c468d.png)

**Comment by jeremy447** [comment]
It seem that happen in web pages too

![capture d ecran de 2016-08-06 17-09-51](https://cloud.githubusercontent.com/assets/17159065/17457477/a4bc84fa-5bf9-11e6-9f8a-83940a70592d.png)

**Comment by jeremy447** [comment]
I think it's the Gnome Arc theme (not the Firefox one) that generate these small button.

**Comment by horst3180** [comment]
Firefox has problems with the theme rendering on GTK 3.20. I can't fix this.

**Comment by jeremy447** [comment]
Ok thanks.
