### ISSUE TITLE
Troubles with FF 47

### ISSUE THREAD

**Issue by DeepDlueIV** [horst3180/arc-firefox-theme#79]
Mint
Fox 47.0 stable 
After using this awesome theme above 3 month on this setup ,Suddenly unsupported and not available  for ff47 here https://addons.mozilla.org/en-US/firefox/addon/arc-darker-theme/
idk y

**Comment by fossfreedom** [comment]
distro specific issue - why has mint not moved to firefox 48?

download the 47 xpi's here - or better still upgrade https://github.com/horst3180/arc-firefox-theme/releases
