### ISSUE TITLE
New version doesn't work on windows

### ISSUE THREAD

**Issue by tivervac** [horst3180/arc-firefox-theme#8]
I know Windows isn't supported, but it works quite well actually.
Trying to install version 40.20150820 doesn't work, firefox complains that the theme is not compatible with 40.0.2.
Maybe updating `minVersion` to `40.0.0` and `maxVersion` to `42.*.*` in `install.rdf` could fix this?

**Comment by horst3180** [comment]
Did it work with the previous release? I'm running 40.0.2 too so the minVersion seems to work correctly. The thing that changed is that I added specific target platforms for the theme, i.e. Linux and BSD.
I'm currently working on making the theme more standalone which, most likely, would make it more compatible with other platforms.

**Comment by tivervac** [comment]
Yes, the previous release worked :)

**Comment by tivervac** [comment]
No changes with the new version. I can try to get it to work myself in a couple of days when I've got some free time on my hands, can't promise anything though.

**Comment by horst3180** [comment]
The theme should now install on all platforms. See here https://github.com/horst3180/arc-firefox-theme/releases/tag/40.20150911
There may be bugs, because I can test it only on Linux.

**Comment by tivervac** [comment]
It does indeed install once again, many thanks!
