### ISSUE TITLE
Firefox menu breaks in Dev Edition 50, Nightly 51

### ISSUE THREAD

**Issue by jaromero** [horst3180/arc-firefox-theme#80]
Firefox Developer Edition just updated to v50, and it seems there has been changes to the menu, because now it looks like this, and nothing is clickable or even responds to mouse hover (using the theme from AMO):

![screenshot from 2016-08-05 10-37-31](https://cloud.githubusercontent.com/assets/794031/17441942/14f12110-5af9-11e6-8266-4bfd93c4f934.png)

Everything else seems to be working fine. I also have HTitle but it makes no difference whether it's enabled or not.

This also happens in Nightly (v51, clean profile screenshot; probably also in v50 but I didn't test it there):

![screenshot from 2016-08-05 10-46-41](https://cloud.githubusercontent.com/assets/794031/17442178/263d3778-5afa-11e6-9cba-b356a63dc530.png)

**Comment by thebettersort** [comment]
I am seeing the same issue.

**Comment by ghost** [comment]
I'm having the same issue. On Firefox 50 it was fine.

**Comment by moriel5** [comment]
We already have 3 threads about this.
This one: #74 ; and this one: #68 .

**Comment by jaromero** [comment]
You're right, apologies. Not sure how I missed those.

Closing this one.
