### ISSUE TITLE
Install is not working

### ISSUE THREAD

**Issue by ErraticFox** [horst3180/arc-firefox-theme#81]
Hello, I'm using Ubuntu 16.04 and I'm trying to install this but both methods seem not to work.

The manual method doesn't work, I ran even with the options to disable the two except the one I wanted and restarted. Nothing happened. The xpi doesn't work I have autoconf and automake installed but I get the error saying `cp: cannot stat './arc-firefox-theme-light/chrome/browser/sass/browser-light.css': No such file or directory` and the FireFox store installation seems to do nothing either.

**Comment by fossfreedom** [comment]
if it helps you can install via gdebi using our arc-firefox-theme package

wget the package from here - https://launchpad.net/~budgie-remix/+archive/ubuntu/ppa

**Comment by ErraticFox** [comment]
Kind of new, so didn't exactly know how to wget a deb package from ppa. Though, I just refreshed FF and it somehow displayed the theme right after it opened back up.
