### ISSUE TITLE
Not compatible with firefox 49

### ISSUE THREAD

**Issue by ghost** [horst3180/arc-firefox-theme#91]
When I try to download from Mozilla.org it says:
Not available for Firefox 49.0

I'm not sure if i should install it manually? if it's not supported what's the point?

**Comment by fossfreedom** [comment]
firefox 50 was released today - suggest make sure you have that version installed then you'll be able to install the addon.

**Comment by ghost** [comment]
Hi fossfreedom, my Archlinux is up-to-date but haven't got the new firefox 50 yet.
I'd rather wait for the Arch team to add it to the repository than to download it manually.
thanks
