### ISSUE TITLE
Pocket Icon Bug in Firefox 50

### ISSUE THREAD

**Issue by ghost** [horst3180/arc-firefox-theme#93]
The Pocket Toolbar Icon is displayed incorrectly in Firefox 50. Looks like the whole icon sprite is shown. Reinstalling of the Theme didn't fix it. (Fixed only the Issue mentioned in #92) 

The Pocket Icon is displayed correctly with the Standard Theme, see Screenshots:

![arc-dark-theme](https://cloud.githubusercontent.com/assets/9143480/20452402/ffb31b2e-ae08-11e6-8f54-3e10f7327da2.png)
![standard-theme](https://cloud.githubusercontent.com/assets/9143480/20452401/ffb1e498-ae08-11e6-84a2-7bde653dd723.png)

Thx

(Using Ubuntu Gnome 16.04)

**Comment by aliaksandrb** [comment]
Confirmed on **FF 53.0 (64-bit**).
And just in case: I have high-definition display 3200x1800 with a scaling factor x2.

Thanks!

**Comment by ghost** [comment]
Closing here, cause firefox >= 57 isn't compatible with this theme anymore. Made a minimal theme overriding some parts of the dark quantum standard theme. if anyone wants to take a look:
https://github.com/jens-t/firefox-theme-arc-darker-flat
