### ISSUE TITLE
e10s support?

### ISSUE THREAD

**Issue by shavitush** [horst3180/arc-firefox-theme#95]
Whenever I use the theme, `about:support` says:

> Multiprocess Windows 0/1 (Disabled by addons)

Is it possible to make the theme work with e10s (or the WebExtensions API)?

**Comment by horst3180** [comment]
It works with e10s, you have to force enable it. Firefox automatically disables e10s if you have addons installed. Maybe some addons have already been tested and whitelisted, but apparently this theme isn't one of them.

**Comment by shavitush** [comment]
I see! I'll report it as a working addon then, thanks for the really quick reply

**Comment by simonbcn** [comment]
This theme disable the multiprocess. 

> ... you have to force enable it. 

It should not be necessary.

> Firefox automatically disables e10s if you have addons installed. 

This isn't true: https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox

This issue should be reopened.

**Comment by fossfreedom** [comment]
@simonbcn strange - this commit marks the addon as compatible - https://github.com/horst3180/arc-firefox-theme/commit/436efe96181eaff50fac1647f140e298fe11569e

Are you using the v51 version of the addon?

**Comment by simonbcn** [comment]
I'm using the git version from [AUR package](https://aur.archlinux.org/packages/arc-firefox-theme-git/): arc-firefox-theme-git 20170123.ec1fc17-1
Firefox 51

When I enable the Arc theme:
![captura de pantalla de 2017 01 30 16 50 03](https://cloud.githubusercontent.com/assets/428231/22429828/4a730dcc-e70c-11e6-8c7a-acfd1af3edcd.png)
