### ISSUE TITLE
Broken video playback controls

### ISSUE THREAD

**Issue by Anerag** [horst3180/arc-firefox-theme#97]
![2016-12-12-192722_638x350_scrot](https://cloud.githubusercontent.com/assets/3858399/21109309/26565390-c0a1-11e6-9d0f-fd3383f62d5f.png)

The video still plays fine, the controls just fly all over the place.

**Comment by raku-cat** [comment]
It does the same thing with audio.
![screenshot](https://puu.sh/uNXxL/0af0f383f7.png)

**Comment by ArchangeGabriel** [comment]
Are you sure it’s the theme? I think I had the same thing without Arc theme (can’t check at the moment).

**Comment by Anerag** [comment]
I had completely forgotten about this report!

@ArchangeGabriel When I made this report I didn't realize this doesn't affect firefox stable. It would seem the new media playback controls (at least on nightly) break old themes. I just figured the theme's maintainers don't want to support beta features so I've been using firefox stable instead.

Still, I'd love to see this fixed.

**Comment by ArchangeGabriel** [comment]
Ah, that’s why. I’m on nightly too. ;)

**Comment by raku-cat** [comment]
I'm on beta, probably the case

**Comment by horst3180** [comment]
Should be fixed now.

**Comment by Anerag** [comment]
Confirmed working, thanks!
